### ISSUE TITLE
Fit indices for regularized partial correlation networks?

### ISSUE THREAD

**Issue by pedro-ribeirosantiago** [KJKan/mcfarland#1]
Thanks Kees-Jan Kan, this is an excellent tutorial of how to compare network and factor models!

I have one question. Is it possible to calculate approximate fit indices (CFI, RMSEA) for network models estimated with GLASSO using the EBICglasso function?

For example:
qgraph::EBICglasso(WAIS_Hungary, n=n_Hungary)

Kind Regards,
Pedro

**Comment by KJKan** [comment]
Dear Pedro,

I believe not. This was actually one of the reasons as to why I first turned to (re)programming networks in OpenMx. Now I would do it Psychonetrics.

What you can do is extract the adjacency matrix and refit the network model in Psychonetrics. This will give you the usual fit statistics for the model, including the CFI and RMSEA.

Best,
Kees-Jan

**Comment by KJKan** [comment]
Dear Pedro,

This is how you would obtain the RMSEA and CFI of your model

library( "psychonetrics" )
library( "qgraph" )
library( "dplyr" )

load( url ( "https://github.com/KJKan/mcfarland/blob/master/WAIS_Hungary.Rdata?raw=true" ) )

n_Hungary <- 1112

nw <- qgraph::EBICglasso( WAIS_Hungary, n=n_Hungary )

adj <- 1*( nw != 0 )

nwModel <- ggm( covs = ( n_Hungary - 1 )/n_Hungary*WAIS_Hungary,
                omega = adj,
                nobs = n_Hungary )

results_nwModel <- nwModel %>% runmodel

fit( results_nwModel )

**Comment by pedro-ribeirosantiago** [comment]
Dear Kees-Jan Kan,

Thanks for the answer and the code. It worked! I found that the partial correlations estimated using ggm with the EBICglasso adjacency matrix were very similar (usually, to a second decimal place) to the partial correlations estimated directly with EBICglasso. 

Thanks once again

Kind regards,
Pedro
